BUNDLE_NAME := CyDeleteSettings
CyDeleteSettings_OBJCC_FILES = CyDeleteSettings.mm

CyDeleteSettings_INSTALL_PATH = /Library/PreferenceBundles

CyDeleteSettings_FRAMEWORKS = UIKit
CyDeleteSettings_PRIVATE_FRAMEWORKS = Preferences

include ../framework/makefiles/common.mk
include ../framework/makefiles/bundle.mk
