BUNDLE_NAME := CyDeleteSettings
CyDeleteSettings_OBJCC_FILES = CyDeleteSettings.mm

CyDeleteSettings_INSTALL_PATH = /Library/PreferenceBundles

CyDeleteSettings_FRAMEWORKS = UIKit
CyDeleteSettings_PRIVATE_FRAMEWORKS = Preferences

TARGET := iphone:7.0:6.0
ARCHS := arm64 armv7

include $(THEOS)/makefiles/common.mk
include $(THEOS)/makefiles/bundle.mk
